version: '3.4'
services:
  flight_predictions_db:
    image: mysql:8.0.33
    environment:
      MYSQL_DATABASE: flight_predictions
      MYSQL_USER: root
      MYSQL_PASSWORD: "09121968."
      MYSQL_ROOT_PASSWORD: "09121968."
    ports:
      - 3307:3307
    volumes:
      - "db_data:/var/lib/mysql"


  flask_app:
    image: flask_app
    build:
      context: .
      dockerfile: ./Dockerfile  # Your Dockerfile for the Flask app
    environment:
      DB_HOST: flight_predictions_db
      DB_USER: root
      DB_PASSWORD: "09121968."
      DB_NAME: flight_predictions
      DB_PORT: 3307
    ports:
      - "5000:5000"  # Flask app port
    depends_on:
      - flight_predictions_db  
    command: ["python", "app.py"]

volumes:
  db_data: